config/routes.rb
Rails.application.routes.draw do
  resources :totals, only: [:index, :show]
  resources :pacientes, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enfermedades_previas.rb
class EnfermedadesPrevias < ApplicationRecord
  belongs_to :paciente
end

app/models/informacion_hospitalaria.rb
class InformacionHospitalaria < ApplicationRecord
  belongs_to :paciente
end

app/models/informacion_temporal.rb
class InformacionTemporal < ApplicationRecord
  belongs_to :paciente
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  has_one :informacion_temporal
  has_one :informacion_hospitalaria
  has_one :sintomas
  has_one :enfermedades_previas
end

app/models/sintomas.rb
class Sintomas < ApplicationRecord
  belongs_to :paciente
end

app/models/total.rb
class Total < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: %i[ show edit update destroy ]

  # GET /pacientes or /pacientes.json
  def index
    @pacientes = Paciente.last(50)
  end

  # GET /pacientes/1 or /pacientes/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end
end

app/controllers/totals_controller.rb
class TotalsController < ApplicationController
  before_action :set_total, only: %i[ show edit update destroy ]

  # GET /totals or /totals.json
  def index
    @totals = Total.all
  end

  # GET /totals/1 or /totals/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_total
      @total = Total.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nosonnumeros</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Id inicio de síntomas</th>
      <th>Municipio</th>
      <th>Edad</th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.id_inicio_sintomas %></td>
        <td><%= paciente.municipio %></td>
        <td><%= paciente.edad %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>

app/views/totals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Totals</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Total</th>
    </tr>
  </thead>

  <tbody>
    <% @totals.each do |total| %>
      <tr>
        <td><%= total.fecha.strftime('%Y-%m-%d') %></td>
        <td><%= number_with_delimiter(total.total) %></td>
      </tr>
    <% end %>
  </tbody>
</table>